<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>AgenticDemo.Application</AssemblyName>
    <RootNamespace>AgenticDemo.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Domain/Domain.csproj" />
    <ProjectReference Include="../Infrastructure/Infrastructure.csproj" />
    <ProjectReference Include="../MCP/MCP.csproj" />
  </ItemGroup>
</Project>
